name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_DB=postgres >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env

      - name: Run docker compose
        run: docker compose up -d --build

      - name: Wait building
        run: sleep 5

      - name: Run tests using pytest
        run: docker compose exec web pytest

      - name: Closing containers
        if: always()
        run: docker compose down
